### ISSUE TITLE
Support Setup

### ISSUE THREAD

**Issue by fhk** [silky/fashion#106]
Current progress on getting this running.

setup
=====

<h3>Mac</h3>

> brew install ghc cabal-install

or

download the installer from (here)[https://www.haskell.org/platform/mac.html].

then,

> cabal update

> cd ./nvds-lib

### [Error](https://stackoverflow.com/questions/11022458/cabal-install-fails-when-installing-pango) using cabal install so use brew
> brew install pango

> cabal sandbox init

You'll need to install nvds lib which is in the folder shown below
> cd ./nvds-lib

> cabal install
(note: this currently takes a few minutes? Is this expected?)
### [Error](https://github.com/haskell/cabal/issues/5164)

> cabal get pango-0.13.5.0

### Error

Still getting an error

```
cabal: Leaving directory '/var/folders/0t/j57h3h3x4ns9km96jhb_zmxw3_4my0/T/cabal-tmp-36315/gtk2hs-buildtools-0.13.4.0'
Building lens-4.16.1...
Installed lens-4.16.1
cabal: Error: some packages failed to install:
cairo-0.13.5.0-FlHMbXIytdkJ24AuhwTIIm depends on cairo-0.13.5.0 which failed
to install.
diagrams-cairo-1.4.1-4W03qxIZoMwXpuoIGYWLd depends on diagrams-cairo-1.4.1
which failed to install.
glib-0.13.6.0-8v3ZoQEqpf3Ib0SRPzybZI depends on glib-0.13.6.0 which failed to
install.
gtk2hs-buildtools-0.13.4.0-9uxkFCuHbD1DY12djFrAtw failed during the configure
step. The exception was:
ExitFailure 1
nvds-lib-0.1.0.4-FjJ99jVVqrCJBCSaxbYDg4 depends on nvds-lib-0.1.0.4 which
failed to install.
pango-0.13.5.0-9Ppj0iNVrww8InFTamPfKW depends on pango-0.13.5.0 which failed
to install.

```

Once installed you can goto a project and install and run it as shown below.

<h4>Example</h4>

1. goto a project folder e.g. fashion/Cubic-Limit-Series/
2. run >ghc Setup.

**Comment by silky** [comment]
sorry, you should just use stack - https://docs.haskellstack.org/en/stable/README/

it should just work with that (say the cubic-limit-series one folder):

1. install stack
2. `cd Cubic-Limit-Series`
3. `stack setup`
4. `stack build`
5. `stack exec -- Cubic-Limit-Series -w 1000 -o a.svg`
